pull_request_rules:
    - name: Automatic merge when CI passes
      conditions:
        - status-success=Travis CI - Pull Request
        - base=master
      actions:
        merge:
          method: merge