sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
language: node_js
node_js: stable
os:
  - linux
  - osx
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master  
